AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: And example of a simple instrumented Python Lambda

Parameters:
  NRAccountId:
    Type: String
    Description: Your New Relic account ID; necessary for distributed tracing.
    AllowedPattern: '[0-9]+'

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  NewRelicExample:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      # In this example, we're using the SAM CLI to package and deploy our lambda. SAM will transform this value during the publish step.
      CodeUri: newrelic_example_python/
      Description: A simple Lambda, with New Relic telemetry
      FunctionName: newrelic-example-python
      Handler: newrelic_lambda_wrapper.handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Environment:
        Variables:
          NEW_RELIC_LAMBDA_HANDLER: app.lambda_handler
          NEW_RELIC_ACCOUNT_ID: !Sub ${NRAccountId}
          # NEW_RELIC_EXTENSION_LOG_LEVEL: "INFO"
          # NEW_RELIC_EXTENSION_SEND_FUNCTION_LOGS: "true"
          # NEW_RELIC_EXTENSION_SEND_EXTENSION_LOGS: "true"
          # NEW_RELIC_LOG: "stdout"

      Layers:
        # This layer includes the New Relic Lambda Extension, a sidecar process that sends telemetry,
        # as well as the New Relic Agent for Python, and a handler wrapper that makes integration easy.
        - !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:451483290750:layer:NewRelicPython313:5
      Policies:
        # This policy allows the lambda to know the value of the New Relic licence key. We need this so
        # that we can send telemetry back to New Relic
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !ImportValue NewRelicLicenseKeySecret-NewRelic-LicenseKeySecretARN
Outputs:
  NewRelicExample:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt NewRelicExample.Arn
  NewRelicExampleIamRole:
    Description: "Implicit IAM Role created for Newrelic Example function"
    Value: !GetAtt NewRelicExampleRole.Arn
