AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: And example of a simple instrumented Ruby Lambda

Parameters:
  NRAccountId:
    Type: String
    Description: Your New Relic account ID; necessary for distributed tracing.
    AllowedPattern: '[0-9]+'

Resources:
  NewRelicExample:
    Type: AWS::Serverless::Function
    Properties:
      # In this example, we're using the SAM CLI to package and deploy our lambda. SAM will transform this value during the publish step.
      CodeUri: newrelic_example_ruby/
      Description: A simple Lambda, with New Relic telemetry
      FunctionName: newrelic-example-ruby
      # The handler for your function needs to be the one provided by the instrumentation layer, below.
      Handler: newrelic_lambda_wrapper.handler
      Runtime: ruby3.3
      # Currently, we don't support Image based PackageType
      PackageType: Zip
      Environment:
        Variables:
          # For the instrumentation handler to invoke your real handler, we need this value

          NEW_RELIC_ACCOUNT_ID: !Sub ${NRAccountId}

          NEW_RELIC_EXTENSION_LOG_LEVEL: DEBUG
          
          NEW_RELIC_EXTENSION_SEND_EXTENSION_LOGS: true

          NEW_RELIC_EXTENSION_SEND_FUNCTION_LOGS: true

          NEW_RELIC_LAMBDA_HANDLER: app.App.lambda_handler

          NEW_RELIC_LICENSE_KEY: <YOUR-LICENSE-KEY>

          NEW_RELIC_LOG_ENDPOINT: <YOUR-LOG-ENDPOINT>

          NEW_RELIC_TELEMETRY_ENDPOINT: <YOUR-TELEMETRY-ENDPOINT>
      Layers:
        # This layer includes the New Relic Lambda Extension, a sidecar process that sends telemetry,
        # as well as the New Relic Agent for Ruby, and a handler wrapper that makes integration easy.
        - !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:451483290750:layer:NewRelicRuby33:11
      Policies:
        # This policy allows the lambda to know the value of the New Relic licence key. We need this so
        # that we can send telemetry back to New Relic
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !ImportValue NewRelicLicenseKeySecret-NewRelic-LicenseKeySecretARN
  Logs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: {"Fn::Join": ["", ["/aws/lambda/", {"Ref": "NewRelicExample"}]]}
      # Lambda functions will auto-create their log group on first execution, but it retains logs forever, which can get expensive.
      RetentionInDays: 7
